import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const condensed_roboto = Roboto_Condensed({
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assignment By Karan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${condensed_roboto.className}  antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
